language: python

python:
  - "3.6"

env:
  -DJANGO=2.2 DB=sqlite3

# install requirements
install:
  - pip install --user -r requirements.txt
  - pip install --user coveralls

# To run tests
script:
  - coverage run manage.py test --settings papersquirrel.settings.ci

# send coverage report to coveralls

after_success:
  coveralls
