language: python

python:
  - "3.6"

env:
  global:
    - DJANGO=2.2 DB=sqlite3
    - DJANGO_SETTINGS_MODULE='papersquirrel.settings.ci'

# install requirements
install:
  - pip install -r requirements.txt
  - pip install coveralls

# To run tests
script:
  - coverage run manage.py test

# send coverage report to coveralls

after_success:
  - coveralls
