# Generated by Django 2.2.1 on 2019-06-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('teaser_text', models.TextField(editable=False, max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('download_date', models.DateTimeField(verbose_name='date downloaded')),
                ('author', models.CharField(max_length=250)),
                ('publisher', models.CharField(max_length=250)),
                ('copyright', models.CharField(max_length=250)),
                ('download_url', models.URLField()),
                ('source_html', models.TextField()),
                ('source_markdown', models.TextField()),
                ('wordcount', models.BigIntegerField()),
            ],
        ),
    ]
