# Generated by Django 2.2.1 on 2019-06-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='copyright',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(blank=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_markdown',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='teaser_text',
            field=models.TextField(blank=True, editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='wordcount',
            field=models.BigIntegerField(editable=False),
        ),
    ]
