# Generated by Django 2.2.1 on 2019-06-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0003_auto_20190602_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='wordcount',
            field=models.BigIntegerField(blank=True, editable=False),
        ),
    ]
