# Generated by Django 2.2.1 on 2019-06-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0005_auto_20190602_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='download_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_html',
            field=models.TextField(blank=True),
        ),
    ]
