# Generated by Django 2.2.1 on 2019-06-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0006_auto_20190610_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='download_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date downloaded'),
        ),
    ]
