# Generated by Django 2.2.1 on 2019-06-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0008_auto_20190611_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
