# Generated by Django 2.2.1 on 2019-06-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0009_auto_20190626_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
