# Generated by Django 2.2.1 on 2019-08-19 14:44

from django.db import migrations, models
from squirrel.utils import getMetaData

def add_thumbnails(apps, schema_editor):
    """
    Find thumbnail URLs for existing articles
    """
    Article = apps.get_model('squirrel', 'Article')
    for article in Article.objects.all():
        article.thumbnail_url = getMetaData(article.source_html)["thumbnail"]
        article.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0011_auto_20190626_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RunPython(add_thumbnails),
    ]
